# Generated by Django 5.0 on 2023-12-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Inventories'},
        ),
    ]
